name: Adhahi Monitor Bot

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install selenium webdriver-manager requests

      - name: Run Monitor Script
        run: python adahi_monitor.py
